# Generated by Django 3.2.4 on 2021-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(default='Вы пока не отправляли запросов', max_length=50)),
                ('page', models.CharField(max_length=255)),
            ],
        ),
    ]
