# Generated by Django 3.2.4 on 2021-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='query_id',
            field=models.CharField(default='Вы пока не отправляли запросов', max_length=100),
        ),
    ]
