# Generated by Django 3.2.4 on 2021-06-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_alter_inquiry_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='query_id',
        ),
    ]
