# Generated by Django 3.2.4 on 2021-06-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_inquiry_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='page',
            field=models.URLField(max_length=255),
        ),
    ]
